version: "2.2"

services:
  postgres:
    image: postgres:10.5
    restart: "no"
    ports:
      - 5433:5432
    volumes:
      - "postgres-data-volume:/etc/postgresql/14/data"
    environment:
      TZ: "Europe/Ukraine"
      DB_EXTENSION: pg_trgm
      POSTGRES_DB: academy_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data-volume:
    external: false

